service: daily-review

frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  runtime: python3.8
  memorySize: 512
  timeout: 29
  iamRoleStatements:
      - Effect: Allow
        Action:
          - ses:SendEmail
          - ses:SendRawEmail
        Resource: "*"
        
functions:
  cronHandler:
    handler: handler.run
    environment: ${file(env.yml)}
    events:
      # Invoke Lambda function (UTC-3:00)
      # actual: cron(59 18 ? * SUN-FRI *) | testing: cron(0/10 18 ? * MON-SAT *)
      - schedule: cron(59 18 ? * SUN-FRI *)